### ISSUE TITLE
FieldPermissionSerializerMixin does not find "check_permission" on serializers with "many=True"

### ISSUE THREAD

**Issue by emptyflash** [InterSIS/django-rest-serializer-field-permissions#1]
After trying to set up field based permissions with this library, I discovered I was unable to use permission on serializers with `many=True`. I believe this is likely because when you create a serializer with `many=True` DRF creates a `ListSerializer` to stand in for the serializer a user is creating.

I think a way to solve this problem would be to find some way to get the `check_permission` attribute to be on the `ListSerializer`, possibly by creating a custom list serializer.

What are your thoughts on this? If I can get some feedback I'll look into it more, implement the changes, and submit a PR.

**Comment by JASchilz** [comment]
Sounds good to me. I haven't had my head in Django for a few months so I can't provide any pointers at the moment.

If you can PR in a failing test first, I'll accept on resolution.

**Comment by JASchilz** [comment]
Merged. Will publish to PyPi, version 1.0.0. You folks are invited to update README, otherwise, I'll be able to get around to it in a month.
