### ISSUE TITLE
Update URL to point to github repo, so package is easily discoverable

### ISSUE THREAD

**Issue by JackAtOmenApps** [InterSIS/django-rest-serializer-field-permissions#18]
The URL in setup currently points to a defunct website, rather than the package repo. That means folks coming from PyPi are unlikely to be able to contribute, see issues, etc, because they can't easily find the repo for this package.

**Comment by JASchilz** [comment]
Great point. Thank you!

You should now be able to see the results at https://pypi.org/project/django-rest-serializer-field-permissions/
