### ISSUE TITLE
[Feature] Support for RelatedFields

### ISSUE THREAD

**Issue by ajhodges** [InterSIS/django-rest-serializer-field-permissions#24]
I have a use case where I am using DRF field permissions with `django-rest-framework-json-api`, which uses `RelatedField`s in favor of Serializer fields. The current `SerializerPermissionMixin` is not compatible with `RelatedField`s - but I'm looking for something very similar to that mixin.

**Comment by JASchilz** [comment]
Hey man! It looks like you've got a number of good features in mind with a lot of really solid implementation.

Would you be interested in taking the package off my hands? I haven't been using this package at all for a few years, or even much of Django. The truth is that I can support keeping the package up to date with new versions of Django and DRF, but there's too much spin-up involved for me to do a good job of occasionally evaluating new features.

What are your thoughts?

**Comment by ajhodges** [comment]
Sure, I'd love to help maintain it. My use cases for it are still pretty limited (and seemingly pretty different than most of the existing use cases), so I don't know how confident I'd feel about being the only maintainer, but I'm down to help out in some capacity. It seems like you and the other contributors have a pretty good feel for what this package is all about, and I'd much prefer to have other people sign off on my PRs, especially being that this is a permissions package. I wasn't trying to stage a coup-by-PR :laughing:

**Comment by JASchilz** [comment]
Hi @ajhodges ! As I've mentioned in a couple of other comments, I'm finding that I'm unable to prioritize the time to safely and responsibly evaluate to this project. I've updated my Readme to reflect this.

This looks like a potentially awesome and valuable upgrade, and I regret that I won't be able to include this in the library.
