### ISSUE TITLE
[Feature] Support for JSONField

### ISSUE THREAD

**Issue by ajhodges** [InterSIS/django-rest-serializer-field-permissions#26]
I'd like to use field-permissions with a [JSONField](https://www.django-rest-framework.org/api-guide/fields/#jsonfield).

**Comment by vicdoz8** [comment]
I'm looking for the same. I have a dynamic model that uses a json field to save the data...And I want to allow (only to a certain group) write part of this data.

**Comment by JASchilz** [comment]
OK! I've touched Django recently enough to feel like I can address this.
I'll work to have a release candidate by next weekend.

**Comment by JASchilz** [comment]
Hi folks! I've released https://github.com/InterSIS/django-rest-serializer-field-permissions/commit/2e13a4e415bf66e10bb0deeac03f4eeba0936bdb as version 4.0.0rc2: https://pypi.org/project/django-rest-serializer-field-permissions/4.0.0rc2/

I don't use this plugin enough currently to give it a thorough test. Could you try using this version and let me know if it achieves what you need it to for the JSONField?

**Comment by JASchilz** [comment]
I've released this as 4.0.0. Thank you for letting me know about this deficiency!
